### ISSUE TITLE
Potential Typo in semilattice definition

### ISSUE THREAD

**Issue by code4ghana** [larsrh/website#15]
Thanks for the knowledge Lars!

I think there's some inconsistencies between the informal and the formal semilattice definitions on the 2 lattice definition, but I'm no expert.

[code section link](https://github.com/larsrh/website/blob/8e53b93530cba023c823794030bd295e7e60dc92/topics/crdt/03-lattices.md#there-)

The informal definition
```
The least upper bound of a and b is defined to be a value c where a ≤ b and a ≤ c ...
```
with no mention of the b ≤ c condition.

However the formal definition states it as #3

```
1. c is in M, and
2. a ≤ c, and
3. b ≤ c, and
```

**Comment by larsrh** [comment]
Thanks, I'll take a look.

**Comment by larsrh** [comment]
I believe this is fixed now, could you please check again?

**Comment by code4ghana** [comment]
Looks good!
