### ISSUE TITLE
Better meta tags

### ISSUE THREAD

**Issue by larsrh** [larsrh/website#25]
Missing `<meta name=description>` and `<link rel=canonical>`

**Comment by larsrh** [comment]
`canonical` is there (not sure why @moonglum didn't see it) and I've decided that I'm too lazy for `description`.

**Comment by moonglum** [comment]
Sorry, what did I not see? 😄

**Comment by larsrh** [comment]
You said my page lacked `canonical` links. But they're there :wink:

**Comment by moonglum** [comment]
Okay, did not remember that 😄 Sorry for that 😊
