### ISSUE TITLE
CRDT series, contracts

### ISSUE THREAD

**Issue by indolamine** [larsrh/website#315]
Lars, working my way through your really excellent CRDT primer (and rebuilding the samples in Clojure for fun).
I ran into this in Part 2:

1. any value must be equal to itself (_reflexivity_)

https://github.com/larsrh/website/blob/aa8de7f70020298c646283fe94c014b19d68a4ef/topics/crdt/02-contracts.md?plain=1#L140

I believe that - talking about partial ordering - the obligation here is rather 
"any value must be less than or equal to itself (_reflexivity_)" 

Is this the correct interpretation? In the actual implementation, you're correctly checking for this, not equality, but the description is a bit confusing this way.

Sorry if this is nitpicking... excellent work by the way, I really enjoy it

**Comment by larsrh** [comment]
Thanks @indolamine, I think you're right, will fix this.
